services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-application
    environment:
      PORT: 8000
      MONGODB_URI: "mongodb://admin:password@mongodb:27017"
      MONGODB_DB: "technical_test"
      EXTERNAL_API_BASE_URL: "https://pruebareactjs.test-class.com/Api"
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    restart: "no"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - '8080:8080'
    restart: "no"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:

