services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-application
    environment:
      PORT: ${PORT:-8000}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}
      EXTERNAL_API_BASE_URL: ${EXTERNAL_API_BASE_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    restart: "no"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    ports:
      - '8080:8080'
    restart: "no"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:

